# Generated by Django 4.1.4 on 2023-01-02 08:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('PAST', 'PAST'), ("O'rta", "O'rta"), ('YUQORI', 'YUQORI')], default="O'rta", max_length=50)),
                ('status', models.CharField(choices=[('YANGI', 'YANGI'), ('ALOQA QILGAN', 'ALOQA QILGAN'), ('YUTUQ', 'YUTUQ'), ("YO'QOTILGAN", "YO'QOTILGAN")], default='YANGI', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan vaqti")),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Tahrirlangan vaqti')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
        ),
    ]
