# Generated by Django 4.1.4 on 2023-01-04 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lead',
            options={'ordering': ('name',), 'verbose_name': 'Lead'},
        ),
    ]
